# <font color=darkblue> Machine Learning model deployment with Flask framework</font>

## <font color=Blue>Used Cars Price Prediction Application</font>

### Objective:
1. To build a Machine learning regression model to predict the selling price of the used cars based on the different input features like fuel_type, kms_driven, type of transmission etc.
2. Deploy the machine learning model with the help of the flask framework.

### Dataset Information:
#### Dataset Source: https://www.kaggle.com/datasets/nehalbirla/vehicle-dataset-from-cardekho?select=CAR+DETAILS+FROM+CAR+DEKHO.csv
This dataset contains information about used cars listed on www.cardekho.com
- **Car_Name**: Name of the car
- **Year**: Year of Purchase
- **Selling Price (target)**: Selling price of the car in lakhs
- **Present Price**: Present price of the car in lakhs
- **Kms_Driven**: kilometers driven
- **Fuel_Type**: Petrol/diesel/CNG
- **Seller_Type**: Dealer or Indiviual
- **Transmission**: Manual or Automatic
- **Owner**: first, second or third owner


### 1. Import required libraries

In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

import warnings
warnings.filterwarnings("ignore")

### 2. Load the dataset

In [19]:
df = pd.read_csv('cardata.csv')
df.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

### 3. Check the shape and basic information of the dataset.

In [20]:
## lets check the shape
df.shape

(301, 9)

In [21]:
## Lets check the basic information of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Seller_Type    301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


### 4. Check for the presence of the duplicate records in the dataset? If present drop them

In [22]:
## Check duplicated records in the dataset
len(df[df.duplicated()])

2

In [23]:
## Dropping duplicates
df.drop_duplicates(inplace=True)

In [24]:
## Recheck
len(df[df.duplicated()])

0

### 5. Drop the columns which you think redundant for the analysis.

In [25]:
## Dropping redundant columns
df.drop('Car_Name',axis=1, inplace=True)

### 6. Extract a new feature called 'age_of_the_car' from the feature 'year' and drop the feature year

In [26]:
## Substracting the year od purchase with the current year and extracting the age of the car
df['age_of_the_car'] = 2024 - df['Year']

In [27]:
## Dropping the column year
df.drop('Year',axis=1,inplace=True)
df.head(2)

Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0           3.35           5.59       27000    Petrol      Dealer   
1           4.75           9.54       43000    Diesel      Dealer   

  Transmission  Owner  age_of_the_car  
0       Manual      0              10  
1       Manual      0              11

### 7. Encode the categorical columns

In [28]:
df['Fuel_Type'].unique()

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [29]:
df['Seller_Type'].unique()

array(['Dealer', 'Individual'], dtype=object)

In [30]:
df['Transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [31]:
## Manual Encoding:
df['Fuel_Type'] = df['Fuel_Type'].replace({'Petrol':0, 'Diesel':1, 'CNG':2})
df['Seller_Type'] = df['Seller_Type'].replace({'Dealer':0, 'Individual':1})
df['Transmission'] = df['Transmission'].replace({'Manual':0, 'Automatic':1})

In [32]:
df['Fuel_Type'].unique()

array([0, 1, 2], dtype=int64)

In [33]:
df['Seller_Type'].unique()

array([0, 1], dtype=int64)

In [34]:
df['Transmission'].unique()

array([0, 1], dtype=int64)

In [35]:
## Final dataframe
df.head(2)

Selling_Price  Present_Price  Kms_Driven  Fuel_Type  Seller_Type  \
0           3.35           5.59       27000          0            0   
1           4.75           9.54       43000          1            0   

   Transmission  Owner  age_of_the_car  
0             0      0              10  
1             0      0              11

### 8. Separate the target and independent features.

In [36]:
x = df.drop('Selling_Price', axis=1)
y = df['Selling_Price']

### 9. Split the data into train and test.

In [37]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)

print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(209, 7) (90, 7)
(209,) (90,)


### 10. Build a Random forest Regressor model and check the r2-score for train and test.

In [38]:
## Let us build simple random forest regressor model
rf = RandomForestRegressor()
rf.fit(x_train, y_train)

RandomForestRegressor()

In [39]:
## Let us check the r2-score to see how is our model is performing

y_train_pred = rf.predict(x_train)
y_test_pred = rf.predict(x_test)

r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

print('r2-score train:', r2_train)
print('r2-score test:', r2_test)

r2-score train: 0.9789590407757197
r2-score test: 0.9059481668864107


### 11. Create a pickle file with an extension as .pkl

In [40]:
import pickle
# Saving model to disk
pickle.dump(rf, open('model.pkl', 'wb'))

### 12. Create new folder/new project in visual studio/pycharm that should contain the "model.pkl" file *make sure you are using a virutal environment and install required packages.*

### a) Create a basic HTML form for the frontend

Create a file **index.html** in the templates folder and copy the following code.

In [41]:
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Car Price Prediction</title>

    <style>
        body {
            height: 100%;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: whitesmoke;
            font-family: Verdana, Geneva, Tahoma, sans-serif;
        }

        h1,
        h3 {
            color: rgb(0, 20, 160);
        }

        #main {
            width: 500px;
            margin: auto;
            margin-top: 100px;
        }

        input[type="text"],
        input[type="number"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            border: 1px solid rgb(0, 20, 160);
            font-weight: bold;
        }

        input:focus-within {
            background-color: rgb(191, 222, 255);
        }

        select {
            background-color: rgb(191, 222, 255);
            color: rgb(0, 0, 0);
            font-weight: bold;
            width: 50%;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
        }

        input[type="submit"] {
            background-color: rgb(56, 86, 255);
            color: rgb(255, 255, 255);
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-weight: bold;
        }

        input[type="submit"]:hover {
            background-color: rgb(0, 20, 160);
        }

        #predict {
            margin-top: 5%;
            width: 100%;
            text-align: center;
            color: rgb(0, 0, 0);
            font-size: larger;
            font-weight: bold;
        }

        label {
            color: rgb(0, 0, 128);
            font-weight: bold;
        }
    </style>

</head>

<body>
<div id="main">
    <h1>Enter Car Details</h1>
    <form action="{{ url_for('predict')}}" method="post">
        <input type="text" label="Name" name="Name" placeholder="Car Name" required>
        <input type="number" label='age_of_the_car' name="age_of_the_car" placeholder="Age of the Car (Years)" required>
        <input type="number" label='Present_Price' name="Present_Price" placeholder="Present Price (In Lakhs)"
               step="0.01" required>
        <input type="number" label='Kms_Driven' name="Kms_Driven" placeholder="Kms Driven" required>
        <select name="Fuel_Type" id="Fuel_Type" required>
            <option value="2">Petrol</option>
            <option value="1">Diesel</option>
            <option value="0">CNG</option>
        </select>
        <select name="Transmission" id="research" required="required">
            <option value="1">Manual</option>
            <option value="0">Automatic</option>
        </select>
        </br>
        </br>
        <input type="submit" value="Submit">
    </form>
</div>
<div id="predict">{{prediction_text}}</div>
</body>

</html>

SyntaxError: invalid decimal literal (4018520547.py, line 25)

### b) Create app.py file and write the predict function

In [ ]:
from flask import Flask, render_template, request
import pickle

app = Flask(__name__)
model = pickle.load(open('model.pkl', 'rb'))


@app.route('/')
def index():
    return render_template('index.html')


@app.route("/predict", methods=['POST'])
def predict():
    if request.method == 'POST':
        car_name = request.form.get('Name')
        age_of_the_car = request.form['age_of_the_car']
        Present_Price = float(request.form['Present_Price'])
        Kms_Driven = int(request.form['Kms_Driven'])
        Fuel_Type = request.form['Fuel_Type']
        Transmission = request.form['Transmission']

        prediction = model.predict([[Present_Price, Kms_Driven, Fuel_Type, Transmission, age_of_the_car]])
        output = round(prediction[0], 2)
        prediction_text = 'Resale Value of your ' + car_name + ' is Rs. ' + str(output) + ' Lakhs.'
        return render_template('index.html', prediction_text=prediction_text)


if __name__ == "__main__":
    app.run(debug=True)

### 13. Run the app.py python file which will render to index html page then enter the input values and get the prediction.

In [ ]:
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 126-086-236
127.0.0.1 - - [27/Sep/2023 20:51:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Sep/2023 20:51:34] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [27/Sep/2023 20:51:58] "POST /predict HTTP/1.1" 200 -
127.0.0.1 - - [27/Sep/2023 20:52:27] "POST /predict HTTP/1.1" 200 -

### Happy Learning :)